### ISSUE TITLE
`space list` with longer space names crashes

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/ribose-cli#10]
When `space list` returns some spaces with longer names, the table overflows and causes this error to be shown:

```
/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/terminal-table-1.8.0/lib/terminal-table/table.rb:305:in `recalc_column_widths': Table width exceeds wanted width of 80 characters. (RuntimeError)
	from /.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/terminal-table-1.8.0/lib/terminal-table/table.rb:339:in `column_widths'
```

The table should automatically use a larger width to shown and the command should never crash.

**Comment by abunashir** [comment]
@ronaldtse: This issue was caused by the `terminal-table` gem we are using, I tried to have a look
into the gem see if there is something we can extend to fix this issue but it looks like quite some work and I am not exactly sure if that would be worth it.

The space length would be variable, some would be a smaller word and some could be bit longer, and I think it might create some inconsistency behavior as the table view is not that flexible.

Should we consider truncating the space name when displaying? So smaller name will display normal but if that's long then we truncate those, Eg: `Really really long name Really really  ...'?

**Comment by ronaldtse** [comment]
Yes we can definitely truncate the name. I just wonder if the gem could support auto length?

**Comment by ronaldtse** [comment]
Maybe if we don't give the `width` parameter it would be auto?

**Comment by abunashir** [comment]
Ha ha, I haven't considered that before:) It seems to be helping, bit cluttered but I think that should do the job for now unless we exceed the standard terminal size. Thanks, @ronaldtse.
